flagdefinedquery: ""
flagconfdefinedquery: ""
flagversion: false
define_service: {}
sync_interval: 5
sync_depth: 10
elasticsearch_url: ""
elasticsearch_port: "9200"
elasticsearch_index: ""
highlight: true
start_time: 0
count: 500
log_verbose: false
searchhost: false
